MusicStoreMvc.Web/Controllers/ShoppingCartController.cs
using MusicStoreMvc.Web.BAL;
using MusicStoreMvc.Web.Models;
using MusicStoreMvc.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicStoreMvc.Web.Controllers
{
    //public class ShoppingCartController : Controller
    //{

    //    MusicStoreMvcContext db = new MusicStoreMvcContext();

    //    // GET: ShoppingCart
    //    public ActionResult Index()
    //    {
    //        var cart = ShoppingCart.GetCart(this.HttpContext);

    //        // Set up our ViewModel
    //        var viewModel = new ShoppingCartViewModel
    //        {
    //            CartItems = cart.GetCartItems(),
    //            CartTotal = cart.GetTotal()
    //        };
    //        return View(viewModel);
    //    }

    //    // GET: 
    //    public ActionResult AddToCart(int id)
    //    {
    //        // Retrieve the album from the database
    //        var addedAlbum = db.Albums.Single(album => album.AlbumId == id);
    //        //Add it to the shopping cart
    //        var cart = ShoppingCart.GetCart(this.HttpContext);
    //        cart.AddToCart(addedAlbum);

    //        // Go back to the main store page for more shopping
    //        return RedirectToAction("Index");
    //    }


    //    // AJAX : //ShoppingCart/RemoveFromCart/5
    //    [HttpPost]
    //    public ActionResult RemoveFromcart(int id)
    //    {
    //        // Remove the item from the cart
    //        var cart = ShoppingCart.GetCart(this.HttpContext);

    //        //Get the name of the album to display confirmation
    //        string albumName = db.Carts.Single(
    //            item => item.RecordId == id).Album.Title;

    //        // Remove from cart
    //        int itemCount = cart.RemoveFromCart(id);

    //        // Display the confirmation message
    //        var results = new ShoppingCartRemoveViewModel
    //        {
    //            Message = Server.HtmlEncode(albumName) + " has been removed from your shopping cart.",
    //            CartTotal = cart.GetTotal(),
    //            ItemCount = itemCount,
    //            DeleteId = id
    //        };
    //        return Json(results);
    //    }


    //    // Get : /ShoppingCart/CartSummary
    //    [ChildActionOnly]
    //    public ActionResult CartSummary()
    //    {
    //        var cart = ShoppingCart.GetCart(this.HttpContext);

    //        ViewData["CartCount"] = cart.GetCount();
    //        return PartialView("CartSummary");
    //    }
    //}


    public class ShoppingCartController : Controller
    {
        MusicStoreMvcContext storeDB = new MusicStoreMvcContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedAlbum = storeDB.Albums
                .Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.Carts
                .Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }


}

MusicStoreMvc.Web/Controllers/StoreController.cs
using MusicStoreMvc.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace MusicStoreMvc.Web.Controllers
{
    public class StoreController : Controller
    {

        private MusicStoreMvcContext db = new MusicStoreMvcContext();
        // GET: Store
        public ActionResult Index()
        {
            var genre = db.Genres.Distinct().ToList();
            return View(genre);
        }

        //GET: Store/Browse
        public ActionResult Browse(string genre, int? page)
        {
            var genreModel = db.Genres.Include("Albums")
                .Single(g => g.Name == genre);
            ////var genreModel = db.Genres.Where(g => g.Name == genre)
            ////                           .Select(g => new GenreAlbumView
            ////                           {
            ////                               Id = g.GenreId,
            ////                               Name = g.Name,
            ////                               Albums = g.Albums
            ////                           }).SingleOrDefault();

            //IQueryable<Album> genreAlbums = from g in db.Albums
            //                  where (g.Genre.Name == genre)
            //                  select g;

            //int pageSize = 3;
            //int pageNumber = (page ?? 1);
            //return View(genreAlbums.ToPagedList(pageNumber, pageSize));

            return View(genreModel);
        }

        // GET : Store/Detail
        public ActionResult Detail(int id)
        {
            var album = db.Albums.Include("Artist").Include("Genre").FirstOrDefault(i => i.AlbumId == id);
            return View(album);
        }
       
        public ActionResult BrowseAlbum(string genre, string searchString)
        {
            //IQueryable<Album> albumModel = db.Albums.Where(g => g.Genre.Name == "Pop");
            IQueryable<Album> albums = db.Albums;
            if (!String.IsNullOrEmpty(genre))
            {
                albums = db.Albums.Where(a => a.Genre.Name.ToUpper().Equals(genre.ToUpper()));
            }
            else
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    albums = db.Albums.Where(a => a.Title.ToUpper().Contains(searchString.ToUpper())
                                || a.Genre.Name.ToUpper().Equals(genre.ToUpper())
                                || a.Artist.Name.ToUpper().Contains(searchString.ToUpper()));
                }

            }

            var genres = db.Genres.ToList().Distinct();
            List<SelectListItem> genreList = new List<SelectListItem>();
            foreach(var item in genres)
            {
                genreList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            }
            ViewBag.Genre = genreList;
            return View(albums.ToList());
        }

        //
        // GET: /Store/GenreMenu
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = db.Genres.ToList();
            return PartialView(genres);
        }
    }
}

MusicStoreMvc.Web/Views/Store/Browse.cshtml
@model MusicStoreMvc.Web.Models.Genre
@*@model PagedList.IPagedList<MusicStoreMvc.Web.Models.Album>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />*@



@{
    ViewBag.Title = "Browse Albums";
}

<div class="col-md-8">
    <h3><em>@Model.Name</em> Albums</h3>
    <div class="clearfix"></div>
    <div class="container">
        <div class="clearfix"></div>
        <div class="row">
            @foreach (var album in Model.Albums)
            {
               
                <div class="jumbotron col-md-4" style="list-style: none">
                    <a href="@Url.Action("Detail", new { id = album.AlbumId })">
                        <img alt="@album.Title" src="@album.AlbumArtUrl" class="img-responsive" />
                        <br />
                        <p class="text-center">@album.Title</p>
                    </a>
                </div>
                if ((album.AlbumId % 3 == 0))
                {
                   <div class="clearfix"></div>
                    <div class="row">
                        <hr />
                    </div>
                }
            }
        </div>
    </div>
</div>
@*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))*@

MusicStoreMvc.Web/Views/Store/BrowseAlbum.cshtml
@model IEnumerable<MusicStoreMvc.Web.Models.Album>

@{
    ViewBag.Title = "BrowseAlbum";
}

<h2>BrowseAlbum</h2>

<div>
    @using (Html.BeginForm())
    {
       <p>
            Genre: @Html.DropDownList("genre", (IEnumerable<SelectListItem>)ViewBag.Genre, "--Genre--", new { htmlAttributes = new { @class = "form-control" } })
            Find by name: @Html.TextBox("SearchString")
            <input type="submit" value="Search" />
        </p>
    }

</div>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4 text-center">
                <a href="@Url.Action("Detail", new { id = item.AlbumId })">
                    <img src="@item.AlbumArtUrl" class="img-circle img-responsive" />
                </a>
                    <p class="text-center text-warning">
                        @item.Title<br />
                        By: @item.Artist.Name <br />
                        Genre : @item.Genre.Name <br />
                        <span class="btn btn-default">
                            @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { id = item.AlbumId }, "")
                        </span>
                    </p>
                    
            </div>
          }
    </div>
</div>

MusicStoreMvc.Web/Views/Store/Detail.cshtml
@model MusicStoreMvc.Web.Models.Album

@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlbumArtUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumArtUrl)
        </dd>

    </dl>
</div>
<p>
    <p class="btn btn-info">
        @Html.ActionLink("Add to cart", "AddToCart","ShoppingCart", new { id = Model.AlbumId }, "")
    </p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.AlbumId }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

MusicStoreMvc.Web/Views/Store/GenreMenu.cshtml
@model IEnumerable<MusicStoreMvc.Web.Models.Genre>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.GenreId }) |
            @Html.ActionLink("Details", "Details", new { id=item.GenreId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.GenreId })
        </td>
    </tr>
}

</table>*@

<ul id="categories">
    @foreach (var genre in Model)
    {
        <li>
            @Html.ActionLink(genre.Name, "Browse", "Store", new { Genre = genre.Name }, null)
        </li>
    }
</ul>

MusicStoreMvc.Web/Views/Store/Index.cshtml
@model IEnumerable<MusicStoreMvc.Web.Models.Genre>

@{
    ViewBag.Title = "Index";
}

<h2>Available Genre</h2>
<div class="col-md-3">
    @*<p>
            @Html.ActionLink("Create New", "Create")
        </p>*@
    <table class="table table-responsive table-condensed table-hover">
        @*<tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            </tr>*@

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="/Store/Browse?genre=@item.Name">@Html.DisplayFor(modelItem => item.Name)</a>
                </td>
            </tr>
        }

    </table>
</div>